/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dancing.men;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DancingFrameTest {
    @Test void appHasAGreeting() {
        DancingMenFrame classUnderTest = new DancingMenFrame();
        assertNotNull(classUnderTest, "Form can be created");
    }
}
